Added support for specifying a date for which postmortem to email, also brings Mail to front & converts the message to plain text.

diff --git a/postmortem b/postmortem
--- a/postmortem
+++ b/postmortem
@@ -12,6 +12,9 @@
 #                     recipients from config values.
 # v0.2.1 2012-05-29 - Morgan Aldridge
 #                     Properly escape quotes in email message body.
+# v0.3   2012-12-04 - Morgan Aldridge
+#                     Now brings Mail to front & converts message to plain text.
+#                     Supports specifying past date of postmortem to email.
 # 
 # LICENSE:
 # 
@@ -40,7 +43,7 @@
 
 # info
 tool=$(basename "$0")
-version='0.2'
+version='0.3'
 copyright='Copyright (c) 2012 Morgan T. Aldridge <morgant@makkintosshu.com>'
 
 # global variables
@@ -73,7 +76,8 @@ function usage()
 	  init              initialize postmortems directories
 	  template          open the postmortem template
 	  today             create and/or open postmortem for today
-	  email             compose new email in Mail with postmortem for today
+	  email [date]      compose new email in Mail with postmortem for today (accepts
+	                      optional date: 'yesterday' or 'YYYY-MM-DD' formatted)
 	
 	Configuration:
 	  A configuration file can be created at ~/.postmortem which sets one or more
@@ -242,6 +246,9 @@ function email()
 			tell application "Mail"
 				set theMessage to make new outgoing message with properties {visible:true, subject:"Daily Postmortem ${date}", content:"${body}"}
 				${recipients_clause}
+				activate
+				delay 1
+				tell application "System Events" to keystroke "t" using {command down, shift down} -- convert message to plain text
 			end tell
 		EOS
 		then
@@ -253,6 +260,33 @@ function email()
 	fi
 	
 	$success;
+}
+
+# parse a date out of a date parameter
+function parse_date_param() 
+{
+	local success=true
+	local in_str="$1"
+	
+	# default to today's date which should've been set on launch
+	if [ -z "$in_str" -o "$in_str" == "today" ]; then
+		success=true # do nothing
+	# convert "yesterday" to a date
+	elif [ "$in_str" == "yesterday" ]; then
+		date="$(date -j -v-1d +%Y-%m-%d)"
+		year="$(date -j -v-1d +%Y)"
+		month="$(date -j -v-1d +%m)"
+	# convert a YYYY-MM-DD formatted string to a date
+	elif [[ "$in_str" =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2}$ ]]; then
+		date="$(date -j -f "%Y-%m-%d" "$in_str" +%Y-%m-%d)"	# yes, this is redundant, but it also means it validates the date
+		year="$(date -j -f "%Y-%m-%d" "$in_str" +%Y)"
+		month="$(date -j -f "%Y-%m-%d" "$in_str" +%m)"
+	else
+		echo "ERROR! An invalid date string '$in_str' was specified!"
+		success=false
+	fi
+	
+	$success
 }
 
 # see if any arguments were passed in
@@ -336,6 +370,12 @@ if [ $# -gt 0 ]; then
 					template
 					;;
 				"email")
+					(( i++ ))
+					if [ -n "${argv[$i]}" ]; then
+						if ! parse_date_param "${argv[$i]}" ; then
+							exit 1
+						fi
+					fi
 					email
 					;;
 				*)
